artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "masoudnickparvar/brain-tumor-mri-dataset"
  local_data_file: artifacts/data_ingestion/brain-mri
  unzip_dir: artifacts/data_ingestion/brain-mri/
